theme: jekyll-theme-slate
title: Kyle Gortych git page
description: Current status under development
icon: wizard.png

footer_links:
  - title: Published with
    url: https://pages.github.com
    icon: GitHub Pages
  - title: Icon created by Freepik - Flaticon
    url: https://www.flaticon.com/free-icons/wizard
    icon: wizard icon
