#+TITLE: Org Export to HTML Example
#+DESCRIPTION: Converts Emacs Org file to HTML
#+AUTHOR: Kyle Gortych
#+EXPORT_FILE_NAME: ../pages/org-export-to-HTML.html
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
# #+STYLE: <link rel="stylesheet" type="text/css" href="BLANK/stylesheet.css"/>
#+HTML_HEAD: <link rel="icon" href="../assets/images/wizard.png" type="image/png" />
#+PROPERTY: header-args :eval never-export
#+OPTIONS: num:nil title:nil

#+BEGIN_EXPORT html
<style>
.nav-style-a{
  background-color: #ddd;
  border: none;
  padding: 5px 10px;
  margin: 4px 2px;
  cursor: pointer;
  margin: 5px 5px 5px 5px;
}

.nav-style-a:hover {
  background-color: #f1f1f1;
}

.dropbtn {
  background-color: #ddd;
  color: black;
  padding: 5px 10px;
  font-size: 16px;
  border: none;
  cursor: pointer;
  margin: 5px 5px 5px 5px;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 5px 10px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: #f1f1f1;
}
</style>
#+END_EXPORT

#+BEGIN_EXPORT html
<header style="display: flex; flex-direction: column;">
<img style="align-self: center; width: 300px; height: auto;" src="../assets/images/emacs.svg" alt="img">
<h1 style="align-self: center; font-size: 30px;">Org Export to HTML</h1>
<nav style="font-size: 16px; margin-bottom: 5px; margin-top: 5px; text-align: center;">
  <a style="color: black;" class="nav-style-a" href="../index.html">Home</a>
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn">Pages</button>
      <div id="myDropdown" class="dropdown-content">
        <a href="./org-export-to-HTML.html">About Org Mode</a>
      </div>
  </div>
</nav>
<nav style="font-size: 16px; margin-bottom: 15px; margin-top: 5px; text-align: center;">
  <a style="color: black;" class="nav-style-a" href="na">LinkedIn</a>
  <a style="color: black;" class="nav-style-a" href="https://github.com/KyleGortych">GitHub</a>
  <a style="color: black;" class="nav-style-a" href="">Resume</a>
</nav>
<br><br>
</header>
#+END_EXPORT

** Org Export
This is a paragraph for the first heading. In org mode it is converted to the appropriate tags. Org mode has lots of features. One of the features are snipits. Snippets are blocks of code in orgmode that allow one to run diffrent languages and even shells within one org document. This is usefull because, one org mode doc can essentially be included in a project with various languages and run them all interactively showing parts of the whole programs operation.

** Paragraphs
#+BEGIN_EXPORT html
<div style="display: flex; flex-direction: row; font-size: 16px;">

  <div style="margin-right: 20px; width: 50%;">
  Paragraph one here is accomplished with an org tag #​+BEGIN​_EXPORT html to directly input the html as is. Lastly using the html div tag, flex box, and margin settings. If you use the pre tag to maunaly format, the exported txt will end up being encased in a text code block from orgs style backend. While this is more verbose than using the pre tag you don't have to worry about orgs backend.
  </div>

  <div style="width: 50%;">
  Paragraph two here. This is the continuation of the second paragraph. Using this method helps with formatting. If you use the pre tag to maunaly format, the exported txt will end up being encased in a box from orgs style backend.
  </div>

</div>
<br><br>
#+END_EXPORT

** Flexbox and Orgmode
Orgmode's backend works nicely with the use of flexbox. While using orgmode I have found that some features like the pre tag and float will not align sections appropriately. To align elements horizontally, flexbox seems to work best.

#+begin_src org
,#+BEGIN_EXPORT html
<div style="display: flex; flex-direction: row; font-size: 16px;">

  <div style="margin-right: 20px; width: 50%;">
  Paragraph one here is accomplished with an org tag #​+BEGIN​_EXPORT html to directly input the html as is. Lastly using the html div tag, flex box, and margin settings. If you use the pre tag to maunaly format, the exported txt will end up being encased in a text code block from orgs style backend. While this is more verbose than using the pre tag you don't have to worry about orgs backend.
  </div>

  <div style="width: 50%;">
  Paragraph two here. This is the continuation of the second paragraph. Using this method helps with formatting. If you use the pre tag to maunaly format, the exported txt will end up being encased in a box from orgs style backend.
  </div>

</div>
<br><br>
,#+END_EXPORT
#+end_src

** The Syntax for Lists
Unordered lists are started in org with a plus or minus sign. To show this an org code block is used with escape characters to demonstrate the org syntax from the exported html output.

#+html: <div style="display: flex; flex-direction: row; gap: 10px;">

#+html: <div style="width: 50%;">
  #+begin_src org
  ​+ bread
  ​+ milk
  ​+ eggs
  #+end_src
#+html: </div>

#+html: <div style="width: 50%;">
  + bread
  + milk
  + eggs
#+html: </div>

#+html: </div>

#+html: <div style="display: flex; flex-direction: row; gap: 10px;">

#+html: <div style="width: 50%;">
  #+begin_src org
  1. bread
  2. milk
  3. eggs
  #+end_src
#+html: </div>

#+html: <div style="width: 50%;">
  1. bread
  2. milk
  3. eggs
#+html: </div>

#+html: </div>

** Examples of Snippets
One enables a snippet within an org doc by using...
+ 'Space-i-s' or...
+ <s tab completion general snippet
+ #+begin-src language-name :exports both
+ #+end-src
+ C-c C-c runs

** Python example

#+begin_src python :exports both
def foo(x):
    if x>0:
        return x+1
    else:
        return x-1

return foo(5)
#+end_src

#+RESULTS:
: 6

** Rust example

#+name: Rust
#+begin_src rust :exports both
fn main() {
    println!("pi value is {}", get_pi());
}

fn get_pi() -> f64 {
    22.0 / 7.0
}
#+end_src

#+RESULTS: Rust
: pi value is 3.142857142857143

# html_head: <base target="_blank"> messes with toc

** List of references in org
The examples below will add spaces between each list or prevent opening link in a new tab which is undesirable.

Note this is an org code block which means escape characters must be used. The comma is used before the hash and plus sign. To have a link as plain text in an org code block specific to org syntax, use a zero width char by typing C-x 8 enter then type zero width char, lastly hit enter again making sure the cursor is in the correct position.

#+begin_src org
,#+html_head: <base target="_blank">

,#+ATTR_HTML: :target _blank
​+ [[LINK]​[DESCRIPTION]]
,#+ATTR_HTML: :target _blank
​+ [[LINK]​[DESCRIPTION]]

​+ @@html:<p>txt <a href="url" target="_blank" rel="noopener noreferrer">link</a></p>@@
​+ @@html:<p>txt <a href="url" target="_blank" rel="noopener noreferrer">link</a></p>@@

,#+begin_src html
<div>
    <ul>
        <li><p>txt <a href="url" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>txt <a href="url" target="_blank" rel="noopener noreferrer">link</a></p></li>
    </ul>
</div>
,#+end_src
#+end_src

Here is the appropriate format
#+begin_src html
<p>Still being resolved</p>
#+end_src

** Exporting the org file in Emacs
To export use 'SPACE-m-e' then 'h' for HTML. Lastly type 'h' or 'o' depending on if you want to open the file in a browser to see the changes.

** References

#+BEGIN_EXPORT html
<footer>
    <ul>
        <li><p>DT youtube ref <a href="https://www.youtube.com/watch?v=K6S-AKm5snc&t=141s " target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>Orgmode website <a href="https://orgmode.org/" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>org export turorial <a href="https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>org turorial <a href="https://emacsclub.github.io/html/org_tutorial.html#sec-6-1" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>distrotube's website <a href="https://distro.tube/index.html" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>org code block example escape chars <a href="https://orgmode.org/manual/Literal-Examples.html" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>org code block escape char for links and lists ie plus <a href="https://orgmode.org/manual/Escape-Character.html" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>org export html <a href="https://orgmode.org/manual/Quoting-HTML-tags.html" target="_blank" rel="noopener noreferrer">link</a></p></li>
        <li><p>Icon created by Freepik - Flaticon <a href="https://www.flaticon.com/free-icons/wizard" title="wizard icons" target="_blank" rel="noopener noreferrer">wizard icon</a></p></li>
    </ul>
</footer>
#+END_EXPORT
